name: Deploy to Raspberry Pi

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Raspberry Pi via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.PI_SSH_PRIVATE_KEY }}
        script: |
          echo "✅ Connected to Raspberry Pi"
          /home/matheaghi/src/librarian/librarian/deploy.sh
